name: Testing on push

on: push

env:
  REACT_APP_API_URL: https://w6-chwe-edgaralcolea-back.herokuapp.com/robots/

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
